#!/bin/bash
# -*- Coding: utf-8-unix -*-
# 音楽CDからWAVEとCUEシート作成
# ファイル上書きチェックしてないので注意

# CDDB サーバ http://freedbtest.dyndns.org/
cddb_server="freedbtest.dyndns.org:80:/~cddb/cddbutf8.cgi"

cdrdao read-cd --device /dev/cdrom --with-cddb \
--cddb-servers "$cddb_server" --datafile CDImage.bin CDImage.toc
sox -t cdda CDImage.bin CDImage.wav
cueconvert -i toc -o cue CDImage.toc CDImage.cue

# printf すると日本語の文字化けが直る
printf "$(cat CDImage.cue)\n" | sed -e '/^MESSAGE/d' -e '/^$/d' \
-e 's/CDImage\.bin/CDImage\.wav/g' > CDImage.cue.tmp
mv CDImage.cue.tmp CDImage.cue

# ファイル名をTITLEと同じにする
# やっつけ処理で上手くいかないかも
TITLE=$(grep TITLE CDImage.cue | head -1 | egrep -o '".*"' | \
sed -e 's/^"//' -e 's/"$//' \
-e "y@\"\/\<\>\\\*\:\?\|@”／＜＞￥＊：？｜@")
if [ "$TITLE" ]; then
  mv CDImage.wav "$TITLE".wav
  TITLE=$(echo -n "$TITLE" | sed 's/&/\\\&/g')
  sed "s/CDImage/$TITLE/g" CDImage.cue > "$TITLE".cue
  rm CDImage.bin CDImage.cue CDImage.toc
else
  rm CDImage.bin CDImage.toc
fi
