#!/bin/bash
if [ $# -ne 1 ]; then
   echo "cdencode (flac,ape,tta,wv)" 1>&2 
   exit 1 
fi
audiocue
CUENAME=`ls -t *.cue | head -n 1`
echo $CUENAME
MAKEENC=`basename "$CUENAME" cue`
echo $MAKEENC
ENCMODE=waveto$1
echo $ENCMODE
$ENCMODE "$MAKEENC"
exit 0

